<?php

namespace App\Socialite\Two;

use Laravel\Socialite\Two\AbstractProvider;
use Laravel\Socialite\Two\ProviderInterface;
use Laravel\Socialite\Two\User;

class OutbrainProvider extends AbstractProvider implements ProviderInterface
{
    /**
     * Auth URL
     *
     * @param string $state
     * @return string
     */
    protected function getAuthUrl($state)
    {
        return $this->buildAuthUrlFromBase('https://api.outbrain.com/amplify/v0.1/login', $state);
    }

    /**
     * Url for getting token.
     *
     * @return string
     */
    protected function getTokenUrl()
    {
        return 'https://api.outbrain.com/amplify/v0.1/login';
    }

    public function getAccessTokenResponse($code)
    {
        $response = $this->getHttpClient()->post($this->getTokenUrl(), [
            'headers' => ['Accept' => 'application/json'],
            'auth' => '',
        ]);

        return json_decode($response->getBody(), true);
    }

    protected function formatScopes(array $scopes, $scopeSeparator)
    {
        return parent::formatScopes($scopes, $scopeSeparator); // TODO: Change the autogenerated stub
    }

    protected function getUserByToken($token)
    {
        // There is no User managing possibility in outbrain amplify API.
    }

    protected function mapUserToObject(array $user)
    {
        // There is no User managing possibility in outbrain amplify API.
    }
}